version: '2'
services:
    vm-app:
        image: vm
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://vm-postgresql:5432/vm
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    vm-postgresql:
        extends:
            file: postgresql.yml
            service: vm-postgresql
